global:
  scrape_interval: 30s
  scrape_timeout: 10s

scrape_configs:
  - job_name: flask
    metrics_path: /metrics
    static_configs:
      - targets:
          - 'flask:5000'
  - job_name: nginx
    metrics_path: /metrics
    static_configs:
      - targets:
          - 'nginx-exporter:4040'